apiVersion: apps/v1
kind: Deployment
metadata:
  name: keel
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: keel
  template:
    metadata:
      labels:
        app: keel
    spec:
      containers:
      - name: keel
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: POLL
          value: "true"
        - name: POLL_INTERVAL
          value: "60"
        - name: LOG_LEVEL
          value: "info"